bootanim.rc
surfaceflinger.rc
update_verifier.rc
installd.rc
keystore.rc
gatekeeperd.rc
tombstoned.rc
cameraserver.rc
vendor.vivo.hardware.biometrics.fingerprint@
feature_enabler_client.rc
android.hardware.camera.provider@
android.hardware.graphics.composer@
vendor.qti.hardware.display.composer-service.rc
vivocameraserver.rc
vendor.vivo.hardware.vibrator_hall@
vendor.vivo.hardware.nativecamera.provider@
vendor.vivo.hardware.camera3rd.provider@
vendor.vivo.hardware.camera.cameralog@
android.hardware.thermal@2.0-service.qti-v2.rc
imsdaemon.rc
ims_rtp_daemon.rc
ims-dataservice-daemon.rc
init.zygote64.rc
boringssl_self_test.rc
tango-binfmt.rc
vendor.qti.camera.provider
flags_health_ch