
#
/system/framework/framework.jar
#
/system/framework/framework.jar
0
(/system/framework/framework-graphics.jar37
0
(/system/framework/framework-graphics.jar37
0
(/system/framework/framework-location.jar37
0
(/system/framework/framework-location.jar37

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
E
=/system/framework/framework-ondeviceintelligence-platform.jar37
E
=/system/framework/framework-ondeviceintelligence-platform.jar37
+
#/system/framework/framework-nfc.jar36
+
#/system/framework/framework-nfc.jar36
"
/system/framework/tcmiface.jar
"
/system/framework/tcmiface.jar
'
#/system/framework/telephony-ext.jar
'
#/system/framework/telephony-ext.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/QPerformance.jar
&
"/system/framework/QPerformance.jar
'
#/system/framework/UxPerformance.jar
'
#/system/framework/UxPerformance.jar
#
/system/framework/WfdCommon.jar
#
/system/framework/WfdCommon.jar
(
$/system/framework/vivo-framework.jar
(
$/system/framework/vivo-framework.jar
$
 /system/framework/vivo-media.jar
$
 /system/framework/vivo-media.jar
+
'/system/framework/framework-adapter.jar
+
'/system/framework/framework-adapter.jar
'
#/system/framework/soc-framework.jar
'
#/system/framework/soc-framework.jar
/
+/system/framework/vivo-camera-framework.jar
/
+/system/framework/vivo-camera-framework.jar
(
$/system/framework/vivo-vgcclient.jar
(
$/system/framework/vivo-vgcclient.jar
+
'/system/framework/vivo-coworkclient.jar
+
'/system/framework/vivo-coworkclient.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar